import React,{useCallback,useEffect,useRef,useState} from 'react';
import {Capacitor} from '@capacitor/core';
import {BarcodeFormat,BarcodeScanner,LensFacing} from '@capacitor-mlkit/barcode-scanning';
import {Camera,CameraOff,RefreshCw,ScanLine,Settings,X} from 'lucide-react';
import {businessQrService,businessQrToken,type QrBusiness} from '../services/businessQrService';

type DetectorResult={rawValue:string};
type DetectorInstance={detect:(source:HTMLVideoElement)=>Promise<DetectorResult[]>};
type DetectorConstructor=new(options:{formats:string[]})=>DetectorInstance;
type ScannerState='starting'|'scanning'|'denied'|'unsupported'|'invalid';

export function QrScannerModal({open,onClose,onResolved}:{open:boolean;onClose:()=>void;onResolved:(token:string,business:QrBusiness)=>void}){
  const videoRef=useRef<HTMLVideoElement>(null);const streamRef=useRef<MediaStream|null>(null);const frameRef=useRef<number|null>(null);const nativeRef=useRef(false);
  const [state,setState]=useState<ScannerState>('starting');const [message,setMessage]=useState('');const [manual,setManual]=useState('');
  const isNative=Capacitor.isNativePlatform();
  const stop=useCallback(()=>{if(frameRef.current!==null)cancelAnimationFrame(frameRef.current);frameRef.current=null;streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null;if(nativeRef.current){nativeRef.current=false;document.body.classList.remove('barcode-scanner-active');void BarcodeScanner.stopScan().catch(()=>undefined);void BarcodeScanner.removeAllListeners().catch(()=>undefined)}},[]);
  const resolve=useCallback(async(raw:string)=>{const token=businessQrToken(raw);if(!token){setState('invalid');setMessage("This QR isn't linked to a business on our platform.");return}try{const {business}=await businessQrService.resolve(token);stop();onResolved(token,business)}catch(error){setState('invalid');setMessage(error instanceof Error?error.message:"This QR isn't linked to a business on our platform.")}},[onResolved,stop]);
  const startNative=useCallback(async()=>{let permission=await BarcodeScanner.checkPermissions();if(permission.camera==='prompt'||permission.camera==='prompt-with-rationale')permission=await BarcodeScanner.requestPermissions();if(permission.camera!=='granted'){setState('denied');setMessage('Camera access is off. Enable Camera Access in Settings, then try again.');return}nativeRef.current=true;document.body.classList.add('barcode-scanner-active');await BarcodeScanner.addListener('barcodesScanned',event=>{const raw=event.barcodes[0]?.rawValue;if(raw)void resolve(raw)});await BarcodeScanner.addListener('scanError',event=>{setState('invalid');setMessage(event.message||'Camera could not scan this code. Please try again.')});setState('scanning');await BarcodeScanner.startScan({formats:[BarcodeFormat.QrCode],lensFacing:LensFacing.Back})},[resolve]);
  const startWeb=useCallback(async()=>{const Detector=(globalThis as unknown as {BarcodeDetector?:DetectorConstructor}).BarcodeDetector;if(!Detector){setState('unsupported');return}const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});streamRef.current=stream;if(!videoRef.current)return;videoRef.current.srcObject=stream;await videoRef.current.play();setState('scanning');const detector=new Detector({formats:['qr_code']});let busy=false;const scan=async()=>{if(!videoRef.current||!streamRef.current)return;if(!busy){busy=true;try{const codes=await detector.detect(videoRef.current);if(codes[0]?.rawValue){await resolve(codes[0].rawValue);return}}catch{}finally{busy=false}}frameRef.current=requestAnimationFrame(scan)};frameRef.current=requestAnimationFrame(scan)},[resolve]);
  const start=useCallback(async()=>{stop();setMessage('');setState('starting');try{if(isNative)await startNative();else await startWeb()}catch(error){stop();setState('denied');setMessage(error instanceof DOMException&&error.name==='NotAllowedError'?'Camera access is off. Enable Camera Access in Settings, then try again.':'Camera could not be started. Please try again.')}},[isNative,startNative,startWeb,stop]);
  useEffect(()=>{if(open)void start();else stop();return stop},[open,start,stop]);
  if(!open)return null;
  return <div id="qr-scanner-modal" className="fixed inset-0 z-[80] flex items-end bg-slate-950/70 sm:items-center sm:justify-center"><div className="w-full overflow-hidden rounded-t-3xl bg-white sm:max-w-md sm:rounded-3xl"><div className="flex items-center justify-between border-b px-5 py-4"><div><p className="text-sm font-bold text-slate-950">Scan business QR</p><p className="text-xs text-slate-500">Point your camera at the code</p></div><button onClick={()=>{stop();onClose()}} aria-label="Close scanner" className="grid h-10 w-10 place-items-center rounded-full bg-slate-100"><X size={18}/></button></div><div className="relative aspect-square bg-slate-950"><video ref={videoRef} playsInline muted className="h-full w-full object-cover"/><div className="pointer-events-none absolute inset-[16%] rounded-3xl border-2 border-white/90"><span className="absolute -left-0.5 -top-0.5 h-8 w-8 rounded-tl-3xl border-l-4 border-t-4 border-teal-400"/><span className="absolute -bottom-0.5 -right-0.5 h-8 w-8 rounded-br-3xl border-b-4 border-r-4 border-teal-400"/></div>{state!=='scanning'&&<div className="absolute inset-0 grid place-items-center bg-slate-950/85 p-8 text-center text-white"><div>{state==='starting'?<RefreshCw className="mx-auto h-8 w-8 animate-spin"/>:state==='denied'?<CameraOff className="mx-auto h-9 w-9"/>:<Camera className="mx-auto h-9 w-9"/>}<p className="mt-4 text-sm font-semibold">{message||(state==='unsupported'?'Camera scanning is not supported in this preview. Paste a QR link below.':"This QR isn't linked to a business on our platform.")}</p>{state==='denied'&&isNative&&<button onClick={()=>void BarcodeScanner.openSettings()} className="mt-4 mr-2 rounded-xl bg-white px-4 py-2 text-sm font-bold text-slate-900"><Settings className="mr-2 inline h-4 w-4"/>Settings</button>}<button onClick={()=>void start()} className="mt-4 rounded-xl bg-white px-4 py-2 text-sm font-bold text-slate-900"><RefreshCw className="mr-2 inline h-4 w-4"/>Try again</button></div></div>}</div><div className="space-y-3 p-5"><div className="flex items-center gap-2 text-xs text-slate-500"><ScanLine size={16}/>Only platform business QR codes are accepted.</div><form onSubmit={event=>{event.preventDefault();void resolve(manual)}} className="flex gap-2"><input value={manual} onChange={event=>setManual(event.target.value)} placeholder="Paste QR link" className="h-11 min-w-0 flex-1 rounded-xl border px-3 text-sm"/><button className="rounded-xl bg-teal-700 px-4 text-sm font-bold text-white">Open</button></form></div></div></div>;
}
